<?php
/**
 * @file
 * These are the custom settings for the ckeditor in drupal.
 */

/**
 * Implementation of hook_editor_js_settings_alter().
 */
function ckeditor_settings_editor_js_settings_alter(&$settings) {
  foreach ($settings['editor']['formats'] as &$format) {
    if ($format['editor'] === 'ckeditor') {
      $format['editorSettings']['removePlugins'] = 'pastefromword';
      $format['editorSettings']['forcePasteAsPlainText'] = TRUE;
      $format['editorSettings']['pasteFromWordPromptCleanup'] = FALSE;
    }
  }
}

function ckeditor_settings_entity_embed_alter(&$build, $entity, $context) {
  if (!stristr($context['data-entity-embed-display'], 'image')) {
	$build['#attributes']['class'][] = 'embedded-file';
  }
}
