search_api_solr.solr_request_dispatcher.*:
  type: config_entity
  label: 'Solr Request Dispatcher Config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    minimum_solr_version:
      type: string
      label: 'The minimum version the Solr server'
    environments:
      type: sequence
      sequence:
        type: string
    recommended:
      type: boolean
    request_dispatcher:
      type: mapping
      mapping:
        name:
          type: string
          label: 'The Solr request dispatcher name'
        never304:
          type: boolean
          nullable: true
        lastModFrom:
          type: string
          nullable: true
        etagSeed:
          type: string
          nullable: true
        cacheControl:
          type: search_api_solr.scalar_values
          nullable: true
