name: lexky-d8
recipe: pantheon
config:
  framework: drupal8
  site: lexky-d8
  id: 085efc9d-6f4f-4d02-a80b-9d5cf086a982
services:
  solr:
    type: solr:8
    portforward: true
    core: lexky
    config:
      dir: sites/all/modules/search_api_solr/solr-conf/8.x
