<?php

/**
 * @file
 * Update functions for the Pantheon Advanced Page Cache module.
 */

/**
 * Set override_list_tags to TRUE for backwards compatibility. We recommend manually changing to FALSE for more consistent clearing. See README
 */
function pantheon_advanced_page_cache_update_8001() {
  \Drupal::configFactory()->getEditable('pantheon_advanced_page_cache.settings')->set('override_list_tags', TRUE)->save();
}
