id: d6_recaptcha_settings
label: reCAPTCHA 6 configuration
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: variable
  variables:
    - recaptcha_noscript
    - recaptcha_site_key
    - recaptcha_size
    - recaptcha_secret_key
    - recaptcha_tabindex
    - recaptcha_theme
    - recaptcha_type
  source_module: recaptcha
process:
  site_key: recaptcha_site_key
  secret_key: recaptcha_secret_key
  'widget/theme': recaptcha_theme
  'widget/type': recaptcha_type
  'widget/size': recaptcha_size
  'widget/tabindex': recaptcha_tabindex
  'widget/noscript': recaptcha_noscript
destination:
  plugin: config
  config_name: recaptcha.settings
