# Schema for the configuration files of the Pantheon Advanced Page Cache module.

pantheon_advanced_page_cache.settings:
  type: config_object
  label: 'Pantheon Advanced Page Cache settings'
  mapping:
    override_list_tags:
      type: boolean
      label: 'If entity_list tags should be overridden'
