version: '3'
services:
  solr4:
    image: solr:5
    ports:
      - "8983:8983"
    volumes:
      - ../../solr-conf/4.x:/opt/solr/server/solr/configsets/drupal/conf
    command: bash -c "docker-entrypoint.sh solr start; solr create -c drupal -d server/solr/configsets/drupal/conf -n drupal; solr restart -f"
