contact.form.*.third_party.contact_storage:
  type: mapping
  label: 'Contact form redirection'
  mapping:
    redirect_uri:
      type: string
      label: 'Redirect URI'
    submit_text:
      type: label
      label: 'Submit Text'
    show_preview:
      type: boolean
      label: 'Show preview button'
