<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_alter.
 */
function search_api_solr_legacy_form_search_api_server_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // We need to restrict by form ID here because this function is also called
  // via hook_form_BASE_FORM_ID_alter (which is wrong, e.g. in the case of the
  // form ID search_api_field_config).
  if (
    in_array($form_id, ['search_api_server_form', 'search_api_server_edit_form']) &&
    isset($form['backend_config']['connector_config']['workarounds']['solr_version']['#options'])
  ) {
    $versions = $form['backend_config']['connector_config']['workarounds']['solr_version']['#options'] + [
      '3.6' => '3.x',
      '4.5' => '4.x',
      '5' => '5.x',
    ];
    ksort($versions);
    $form['backend_config']['connector_config']['workarounds']['solr_version']['#options'] = $versions;
  }
}

/**
 *
 */
function search_api_solr_legacy_search_api_solr_configset_template_mapping_alter(&$solr_configset_template_mapping) {
  $template_path = drupal_get_path('module', 'search_api_solr_legacy') . '/solr-conf-templates/';

  $solr_configset_template_mapping += [
    '3.x' => $template_path . '3.x',
    '4.x' => $template_path . '4.x',
    '5.x' => $template_path . '5.x',
  ];
}
