<?php
/**
 * @file
 * Paragraphs jQuery UI Accordion hooks and common functions.
 */

/**
 * Implements hook_theme().
 */
function paragraphs_jquery_ui_accordion_theme() {
  return [
    'paragraphs_jquery_ui_accordion_formatter' => [
      'variables' => ['title' => NULL, 'content' => NULL, 'id' => NULL, 'title_attributes' => NULL, 'content_attributes' => NULL],
      'template' => 'paragraphs-jquery-ui-accordion-formatter',
    ],
  ];
}
