# Schema for the configuration files of the Bootstrap Barrio Subtheme.

lfucg.settings:
  type: theme_settings
  label: 'LFUCG settings'
  mapping:
    lfucg_sidebar_position:
      type: text
      label: 'Sidebar Position'
    lfucg_content_offset:
      type: integer
      label: 'Offset'
    lfucg_sidebar_first_width:
      type: integer
      label: 'Width'
    lfucg_sidebar_first_offset:
      type: integer
      label: 'Offset'
    lfucg_sidebar_second_width:
      type: integer
      label: 'Width'
    lfucg_sidebar_second_offset:
      type: integer
      label: 'Offset'
    lfucg_footer_layout:
      type: text
      label: 'Layout'
    lfucg_fluid_container:
      type: integer
      label: 'Enabled'
    lfucg_button_size:
      type: text
      label: 'Size'
    lfucg_button_outline:
      type: integer
      label: 'Button outline'
    lfucg_navbar_top_position:
      type: text
      label: 'Position'
    lfucg_navbar_top_color:
      type: integer
      label: 'Color'
    lfucg_navbar_top_background:
      type: text
      label: 'Background'
    lfucg_navbar_position:
      type: text
      label: 'Position'
    lfucg_navbar_color:
      type: integer
      label: 'Color'
    lfucg_navbar_background:
      type: text
      label: 'Background'
    lfucg_anchors_fix:
      type: integer
      label: 'Enabled'
    lfucg_anchors_smooth_scrolling:
      type: integer
      label: 'Enabled'
    lfucg_forms_required_has_error:
      type: integer
      label: 'Enabled'
    lfucg_forms_has_error_value_toggle:
      type: integer
      label: 'Enabled'
    lfucg_forms_smart_descriptions:
      type: integer
      label: 'Enabled'
    lfucg_forms_smart_descriptions_limit:
      type: integer
      label: 'Limit'
    lfucg_forms_smart_descriptions_allowed_tags:
      type: text
      label: 'Allowed tags'
    lfucg_popover_enabled:
      type: integer
      label: 'Enabled'
    lfucg_popover_animation:
      type: integer
      label: 'Enabled'
    lfucg_popover_html:
      type: integer
      label: 'Enabled'
    lfucg_popover_placement:
      type: text
      label: 'Placement'
    lfucg_popover_selector:
      type: text
      label: 'Selector'
    lfucg_popover_trigger_autoclose:
      type: integer
      label: 'Enabled'
    lfucg_popover_delay:
      type: integer
      label: 'Enabled'
    lfucg_popover_trigger:
      type: mapping
      mapping:
        hover:
          type: integer
          label: 'Hover'
    lfucg_tooltip_enabled:
      type: integer
      label: 'Enabled'
    lfucg_tooltip_descriptions:
      type: integer
      label: 'Enabled'
    lfucg_tooltip_descriptions_length:
      type: integer
      label: 'Length'
    lfucg_tooltip_animation:
      type: integer
      label: 'Enabled'
    lfucg_tooltip_html:
      type: integer
      label: 'Length'
    lfucg_tooltip_delay:
      type: integer
      label: 'Enabled'
    lfucg_popover_title:
      type: text
      label: 'Title'
    lfucg_popover_content:
      type: text
      label: 'Content'
    lfucg_tooltip_placement:
      type: text
      label: 'Placement'
    lfucg_tooltip_container:
      type: text
      label: 'Container'
    lfucg_tooltip_selector:
      type: text
      label: 'Selector'
    lfucg_tooltip_trigger:
      type: mapping
      mapping:
        hover:
          type: text
          label: 'Hover'
    lfucg_popover_container:
      type: text
      label: 'Container'