<?php
/**
 * @file
 * This is the custom calendar for the LFUCG site.
 */
function lex_calendar_theme($existing, $type, $theme, $path) {
  return [
    'calendar_page' => [
      'variables' => [
        'fc_callback' => NULL
      ]
    ],
    'lex_calendar_event_block' => [
      'variables' => [
        'dates' => NULL,
        'content_type' => '',
        'is_front' => ''

      ]
    ]
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function lex_calendar_preprocess_lex_calendar_event_block(&$variables) {
  // An exception might be thrown.
  try {
    $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  }
  catch (Exception $e) {
    // If the database is not yet available, set the default value.
    $variables['is_front'] = FALSE;
  }
}
