<?php

/**
 * @file
 * General functions and hook implementations.
 *
 * @see http://harvesthq.github.com/chosen/
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Define chosen library url.
 */
define('CHOSEN_WEBSITE_URL', 'http://harvesthq.github.io/chosen');

/**
 * Implements hook_page_attachments().
 */
function chosen_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'chosen/drupal.chosen';

  $chosen_conf = \Drupal::config('chosen.settings');

  $css_disabled_themes = $chosen_conf->get('chosen_disabled_themes');
  if (empty($css_disabled_themes)) {
    $css_disabled_themes = array();
  }

  // Only add the Chosen CSS if it is not disabled for the active theme.
  $theme_name = \Drupal::theme()->getActiveTheme()->getName();
  if (!in_array($theme_name, $css_disabled_themes, TRUE)) {
    $page['#attached']['library'][] = 'chosen_lib/chosen.css';
  }

  $options = array(
    'disable_search' => (bool) $chosen_conf->get('chosen_disable_search'),
    'disable_search_threshold' => (int) $chosen_conf->get('chosen_disable_search_threshold'),
    'search_contains' => (bool) $chosen_conf->get('chosen_search_contains'),
    'placeholder_text_multiple' => $chosen_conf->get('chosen_placeholder_text_multiple'),
    'placeholder_text_single' => $chosen_conf->get('chosen_placeholder_text_single'),
    'no_results_text' => $chosen_conf->get('chosen_no_results_text'),
    'inherit_select_classes' => TRUE,
  );

  $page['#attached']['drupalSettings']['chosen'] = array(
    'selector' => $chosen_conf->get('chosen_jquery_selector'),
    'minimum_single' => (int) $chosen_conf->get('chosen_minimum_single'),
    'minimum_multiple' => (int) $chosen_conf->get('chosen_minimum_multiple'),
    'minimum_width' => (int) $chosen_conf->get('chosen_minimum_width'),
    'options' => $options,
  );
}

/**
 * Implements hook_element_info_alter().
 */
function chosen_element_info_alter(&$info) {
  $info['select']['#pre_render'][] = 'chosen_pre_render_select';

  if (\Drupal::moduleHandler()->moduleExists('date')) {
    $info['date_combo']['#pre_render'][] = 'chosen_pre_render_date_combo';
  }

  if (\Drupal::moduleHandler()->moduleExists('select_or_other')) {
    $info['select_or_other']['#pre_render'][] = 'chosen_pre_render_select_or_other';
  }
}

/**
 * Render API callback: Apply Chosen to a select element.
 *
 * @param array $element
 *   The element.
 *
 * @return array
 *   The element.
 */
function chosen_pre_render_select($element) {
  // If the #chosen FAPI property is set, then add the appropriate class.
  if (isset($element['#chosen'])) {
    if (!empty($element['#chosen'])) {
      // Element has opted-in for Chosen, ensure the library gets added.
      $element['#attributes']['class'][] = 'chosen-enable';
    }
    else {
      $element['#attributes']['class'][] = 'chosen-disable';
      // Element has opted-out of Chosen. Do not add the library now.
      return $element;
    }
  }
  elseif (isset($element['#attributes']['class']) && is_array($element['#attributes']['class'])) {
    if (array_intersect($element['#attributes']['class'], array('chosen-disable'))) {
      // Element has opted-out of Chosen. Do not add the library now.
      return $element;
    }
    elseif (array_intersect($element['#attributes']['class'], array('chosen-enable'))) {
      // Element has opted-in for Chosen, ensure the library gets added.
    }
  }
  else {
    // Neither the #chosen property was set, nor any chosen classes found.
    // This element still might match the site-wide critera, so add the library.
  }

  if (isset($element['#field_name']) && !empty($element['#multiple'])) {
    if (isset($element['#entity_type']) && isset($element['#field_name'])) {
      $field = FieldConfig::loadByName($element['#entity_type'], $element['#field_name']);
      if ($field['cardinality'] != FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED && $field['cardinality'] > 1) {
        $element['#attributes']['data-cardinality'] = $field['cardinality'];
      }
    }
  }

  $element['#attached']['library'][] = 'chosen/drupal.chosen';

  return $element;
}

/**
 * Render API callback: Apply Chosen to a date_combo element.
 *
 * @param array $element
 *   The element.
 *
 * @return array
 *   The element.
 */
function chosen_pre_render_date_combo($element) {
  // Because the date_combo field contains many different select elements, we
  // need to recurse down and apply the FAPI property to each one.
  if (isset($element['#chosen'])) {
    chosen_element_apply_property_recursive($element, $element['#chosen']);
  }
  return $element;
}

/**
 * Render API callback: Apply Chosen to a select_or_other element.
 *
 * @param array $element
 *   The element.
 *
 * @return array
 *   The element.
 */
function chosen_pre_render_select_or_other($element) {
  if ($element['#select_type'] == 'select' && isset($element['#chosen'])) {
    $element['select']['#chosen'] = $element['#chosen'];
  }
  return $element;
}

/**
 * Recurse through an element to apply the chosen property to any select fields.
 * @param array $element
 *   The element.
 *
 * @param integer $chosen_value
 *   Chosen setting
 *
 * @return array
 *   The element.
 */
function chosen_element_apply_property_recursive(array &$element, $chosen_value = NULL) {
  if (!isset($chosen_value)) {
    if (isset($element['#chosen'])) {
      $chosen_value = $element['#chosen'];
    }
    else {
      return;
    }
  }
  if (isset($element['#type']) && $element['#type'] == 'select') {
    $element['#chosen'] = $chosen_value;
  }
  foreach (\Drupal\Core\Render\Element::children($element) as $key) {
    chosen_element_apply_property_recursive($element[$key], $chosen_value);
  }
}
