language: php

dist: trusty

php:
  - 7.1
  - 7.3

env:
  - SOLR_VERSION=4.5.1 SOLR_CORE=d8 SEARCH_API_SOLR_CONF=4.x DRUPAL_BRANCH=8.7.x DRUSH_VERSION=~9.6.0
  - SOLR_VERSION=5.5.4 SOLR_CORE=d8 SEARCH_API_SOLR_CONF=5.x DRUPAL_BRANCH=8.7.x DRUSH_VERSION=~9.6.0
  - SOLR_VERSION=6.6.6 SOLR_CORE=d8 SEARCH_API_SOLR_CONF=6.x DRUPAL_BRANCH=8.7.x DRUSH_VERSION=~9.6.0
  - SOLR_VERSION=6.6.6 SOLR_CORE=d8 SEARCH_API_SOLR_CONF=6.x DRUPAL_BRANCH=8.8.x DRUSH_VERSION=~9.6.0

git:
  # The depth needs to be increased. The default of 50 leads to fatal: reference
  # repository '/home/travis/.cache/composer/vcs/-home-travis-build-mkalkbrenner
  # -search-api-solr/' is shallow.
  depth: 10000

cache:
  directories:
    - $HOME/.composer/cache
    - solr_downloads

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer global require "hirak/prestissimo:^0.3"
  - ls solr_downloads/
  - wget -nc --continue -v --tries=3 --directory-prefix=solr_downloads "http://archive.apache.org/dist/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz"
  - tar -xzf solr_downloads/solr-${SOLR_VERSION}.tgz
  - mysql -e 'CREATE DATABASE drupal;'

install:
  - git tag 999.1.0
  # Make sure we don't fail when checking out projects.
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host git.drupal.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Forward the errors to the syslog so we can print them
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Get the Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 --branch $DRUPAL_BRANCH https://git.drupal.org/project/drupal.git
  - cd $TRAVIS_BUILD_DIR/../drupal
  - composer install
  - composer config repositories.search_api_solr vcs $TRAVIS_BUILD_DIR
  - composer require drupal/search_api:1.x-dev drupal/search_api_autocomplete:1.x-dev drupal/search_api_solr:999.1.0 drupal/facets:1.x-dev drupal/geofield:1.x-dev drush/drush:$DRUSH_VERSION
  - |
    if [ ${DRUPAL_BRANCH} != "8.8.x" ]; then
      composer run-script drupal-phpunit-upgrade
    fi
  # Patch template.
  #########################################
  # to be removed once #2824932 is resolved
  #- cd modules/contrib/search_api
  #- curl https://www.drupal.org/files/issues/2018-12-20/3021717.patch | patch -p1
  #- cd $TRAVIS_BUILD_DIR/../drupal
  #########################################

before_script:
  - export SOLR_INDEX_WAIT=4
  - export SYMFONY_DEPRECATIONS_HELPER=disabled
  - export SIMPLETEST_DB=mysql://root:@localhost/drupal
  - export SIMPLETEST_BASE_URL=http://localhost:8888
  # Start the built-in php web server (mysql is already started) and suppress
  # web server access logs output.
  - php -S localhost:8888 >& /dev/null &
  # Start Solr
  - $TRAVIS_BUILD_DIR/solr-${SOLR_VERSION}/bin/solr start -e techproducts || travis_terminate 1;
  - $TRAVIS_BUILD_DIR/solr-${SOLR_VERSION}/bin/solr create -c d8 -d $TRAVIS_BUILD_DIR/solr-conf/${SEARCH_API_SOLR_CONF} || travis_terminate 1;

script:
  # Run the tests
  - cd $TRAVIS_BUILD_DIR/../drupal
  - vendor/bin/phpunit -c core --group search_api_solr --verbose --debug modules/contrib/search_api_solr/tests/src || travis_terminate 1;

matrix:
  allow_failures:
    - php: 7.1
      env: SOLR_VERSION=6.6.6 SOLR_CORE=d8 SEARCH_API_SOLR_CONF=6.x DRUPAL_BRANCH=8.8.x DRUSH_VERSION=~9.6.0
