_core:
  default_config_hash: DxsZkkrod97cQtkSKNioAnuZewcgL_MHfh1HYLTuAS4
minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 200
jquery_selector: 'select:visible'
search_contains: true
disable_search: false
placeholder_text_multiple: 'Choose some option'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  lex: lex
  seven: '0'
  bartik: '0'
