definitions:
  contact__site_page:
    weight: -44
    menu_name: footer
    parent: ''
    enabled: false
    expanded: false
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
