maxAnalyzedChars: 51200
fragmenter: gap
usePhraseHighlighter: true
highlightMultiTerm: true
preserveMulti: false
regex:
  slop: 0.5
  pattern: blank
  maxAnalyzedChars: 10000
excerpt:
  snippets: 3
  fragsize: 70
  mergeContiguous: false
highlight:
  mergeContiguous: false
  requireFieldMatch: false
_core:
  default_config_hash: 914vBglS7nVnl8EUqBejfUPPRT6wnWYcOhMli6oL4jY
