smtp_host: null
smtp_on: true
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: ''
smtp_password: ''
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: fP57Sd8RjnZMVH3p_R-Yt0tC8j7Z-BuzGMIp6pmrHAI
