smtp_on:
smtp_host:
smtp_hostbackup: ''
smtp_port: ''
smtp_protocol:
smtp_username:
smtp_password:
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging:
prev_mail_system: devel_mail_log
_core:
  default_config_hash: U7C23Wy4M4Eq8X8ExjU4n3yq7PtfU1S-jebw2hikU5g
