smtp_on: null
smtp_host: null
smtp_hostbackup: ''
smtp_port: ''
smtp_protocol: null
smtp_username: null
smtp_password: null
smtp_from: ''
smtp_fromname: ''
smtp_allowhtml: '0'
smtp_test_address: ''
smtp_debugging: null
prev_mail_system: devel_mail_log
_core:
  default_config_hash: U7C23Wy4M4Eq8X8ExjU4n3yq7PtfU1S-jebw2hikU5g
