check:
  disabled_extensions: false
  interval_days: 1
fetch:
  url: ''
  max_attempts: 2
  timeout: 30
notification:
  emails:
    - webmaster@lexingtonky.gov
    - eschwartz@lexingtonky.gov
  threshold: all
