<?php

function atlas_preprocess_menu(&$variables) {
  // expose the url_title so it can be displayed in a tag
  if ($variables['menu_name'] == 'main') {
    foreach($variables['items'] as &$item) {
      foreach($item['below'] as &$below) {
        $below['url_title'] = $below['url']->getOption('attributes')['title'];
      }
    }
  }
}

function atlas_preprocess_form(&$variables) {
  $variables['attributes']['class'] = array('usa-search');
}

