<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\node\Entity\Node;
use \Drupal\Core\Breadcrumb\Breadcrumb;
use \Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_form_alter().
 */
function lex_custom_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  $form['field_keywords']['widget']['add_more']['#value'] = t('Add Another Keyword');
}

// function lex_custom_views_post_execute(ViewExecutable $view) {
//   if ($view->id() == 'solr_search') {
//     foreach($view->result as $key => $result) {
//       $entity = $result->_object->getValue();
//       if (
//         ($entity->bundle() == 'event' || $entity->bundle() == 'meeting') &&
//         (date("Y-m-d H:i:s") > $entity->field_date->value || date("Y-m-d H:i:s") > $entity->field_date_end->value))
//         {
//           unset($view->result[$key]);
//         }
//     }
//   }
// }

/**
 * Implements hook_system_breadcrumb_alter().
 */
function lex_custom_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  // Append the current page title to the breadcrumb for non-admin routes.
  if ($breadcrumb && !\Drupal::service('router.admin_context')->isAdminRoute()) {
    $title = \Drupal::service('title_resolver')->getTitle(\Drupal::request(), $route_match->getRouteObject());
    if (!empty($title)) {
      $breadcrumb->addLink(\Drupal\Core\Link::createFromRoute($title, '<none>'));
    }
  }
}